INSERT INTO PLANET(ID, NAME, TERRAIN, CLIMATE, APPARITIONS_IN_MOVIES)
VALUES ( 1001, 'Teste1', 'Teste1', 'Teste1', 5);
INSERT INTO PLANET(ID, NAME, TERRAIN, CLIMATE, APPARITIONS_IN_MOVIES)
VALUES ( 1002, 'Teste2', 'Teste2', 'Teste2', 2);
INSERT INTO PLANET(ID, NAME, TERRAIN, CLIMATE, APPARITIONS_IN_MOVIES)
VALUES ( 1003, 'Teste3', 'Teste3', 'Teste3', 0);
